MC2-LESSERAFIM/MC2-LESSERAFIM

- MC2-LESSERAFIM.xcodeproj/project.pbxproj
- MC2-LESSERAFIM/ChallengeScreen.swift
- MC2-LESSERAFIM/ChallengeView.swift
- MC2-LESSERAFIM/ContentView.swift
- MC2-LESSERAFIM/OnBoardingScreen.swift
- MC2-LESSERAFIM/ProfileScreen.swift
- MC2-LESSERAFIM/RecordCollectionView.swift
- MC2-LESSERAFIM/RecordView.swift
> [Fix] operations fixed

- MC2-LESSERAFIM.xcodeproj/project.pbxproj
- MC2-LESSERAFIM/Challenge/ChallengeScreen.swift
- MC2-LESSERAFIM/ContentView.swift
- MC2-LESSERAFIM/Model/DataModel.swift
- MC2-LESSERAFIM/OnBoarding/CheckInComplete.swift
- MC2-LESSERAFIM/RecordCollection/RecordCollectionView.swift
- MC2-LESSERAFIM/backgroundView.swift
[ADD] add backgroundView
[Fix] NavigationLink error fixed
[ADD] modify reviewed change
> [ADD] add backgroundView

- MC2-LESSERAFIM.xcodeproj/project.pbxproj
- MC2-LESSERAFIM/Challenge/ChallengeScreen.swift
- MC2-LESSERAFIM/Challenge/RecordSelectionView.swift
- MC2-LESSERAFIM/Components/PageTitle.swift
- MC2-LESSERAFIM/Components/UserNameTextField.swift
- MC2-LESSERAFIM/Extensions/ColorExtension.swift
- MC2-LESSERAFIM/Extensions/ViewExtension.swift
- MC2-LESSERAFIM/OnBoarding/CheckInComplete.swift
- MC2-LESSERAFIM/OnBoarding/CheckInScreen.swift
- MC2-LESSERAFIM/OnBoarding/OnBoardingScreen.swift
- MC2-LESSERAFIM/OnBoarding/OnBoardingTabView.swift
- MC2-LESSERAFIM/OnBoarding/UserCharacter/SelectedUserCharacterScreen.swift
- MC2-LESSERAFIM/OnBoarding/UserCharacter/SmallOnBoarding.swift
- MC2-LESSERAFIM/Profile/ProfileScreen.swift
* 배경까지 적용된 이후에 한번 더 확인할 예정입니다.
[수정된 뷰]
- ChallengeScreen
- PageTitle
- CheckInComplete
- CheckInScreen
- OnBoardingScreen
- OnboardingTabView
- SelectedUserCharacterScreen
- SmallOnBoarding
- ProfileScreen
[추가된 것]
- ColorExtension 
- ViewExtension
- UserNameTextField(커스텀 TextField 컴포넌트)
[문제]
- 기록 모음 뷰는 시뮬레이터에서 탭바가 안 뜰 때가 많아서 확인하기 어렵습니다.
> [MERGE] 디자인(색상 및 폰트 사이즈 등) 수정 머지

- MC2-LESSERAFIM/Challenge/ChallengeScreen.swift
- 준 -> 베리 -> 순서로 PR 작업을 하다가 실행이 코드 들여쓰기 레벨이 꼬여서 못했음
- 수정용 브랜치를 따로 파서 Main에 합치려고 함
> [FIX] 실행이 안되는 버그 수정

- MC2-LESSERAFIM/Assets.xcassets/AccentColor.colorset/Contents.json
- MC2-LESSERAFIM/Challenge/ChallengeScreen.swift
- MC2-LESSERAFIM/Challenge/RecordSelectionView.swift
- MC2-LESSERAFIM/Components/RecordButton.swift
- MC2-LESSERAFIM/OnBoarding/UserCharacter/SelectedUserCharacterScreen.swift
- MC2-LESSERAFIM/Profile/Modal/ImageModalScreen.swift
- MC2-LESSERAFIM/Profile/Modal/NameModalScreen.swift
- MC2-LESSERAFIM/Profile/ProfileScreen.swift
- ProfileScreen
- NameModalScreen
- ImageModalScreen
- SelectedUserCharacterScreen
- RecordSelectionView
- RecordButton
- ChallengeScreen(이슈 해결)
- AccentColor
> [MERGE] 디자인(색상 및 폰트 사이즈 등) 수정 머지 2

- MC2-LESSERAFIM/Challenge/RecordSelectionView.swift
- MC2-LESSERAFIM/Components/RecordButton.swift
1. 버튼 아이콘 이미지 에셋-> 시스템이미지로 수정하여 사용
2. 버튼 온클릭 시 배경에 cornerRadius 추가
[cornerRadius 추가 전]
[cornerRadius 추가 후]
> [CHORE] RecordSelectionView 버튼 아이콘 및 배경 수정

- MC2-LESSERAFIM/Challenge/RecordSelectionView.swift
- MC2-LESSERAFIM/Components/RecordButton.swift
- RecordSelectionView의 사진 버튼 선택하여 액션시트가 올라올 때 버튼 아이콘 및 텍스트 색상 변화
- Color.mainBlack -> Color.white
> [CHORE] 기록선택뷰 버튼 선택 시 버튼 아이콘 및 텍스트 색상 변화

- MC2-LESSERAFIM/ContentView.swift
- 온보드에서 바로 챌린지뷰로 접근할 수 있도록 변경하였습니다.
> [CHORE] 챌린지뷰 바로 접근 

- MC2-LESSERAFIM/Challenge/Record/Painting/CanvusView.swift
- MC2-LESSERAFIM/Challenge/Record/Picture/WritingView.swift
- MC2-LESSERAFIM/Challenge/Record/Writing/RecordWritingView.swift
- MC2-LESSERAFIM/Challenge/RecordSelectionView.swift
- MC2-LESSERAFIM/ContentView.swift
- MC2-LESSERAFIM/OnBoarding/CheckInComplete.swift
- MC2-LESSERAFIM/OnBoarding/CheckInScreen.swift
- MC2-LESSERAFIM/OnBoarding/OnBoardingScreen.swift
- MC2-LESSERAFIM/OnBoarding/UserCharacter/SelectedUserCharacterScreen.swift
- MC2-LESSERAFIM/RecordCollection/RecordCollectionView.swift
add Background to OnboardingView
> [Add] Background to OnboardingView

- MC2-LESSERAFIM/ContentView.swift
> [CHORE] 탭바 아이콘 변경

- MC2-LESSERAFIM/Challenge/ChallengeScreen.swift
- MC2-LESSERAFIM/ContentView.swift
- MC2-LESSERAFIM/OnBoarding/CheckInComplete.swift
- MC2-LESSERAFIM/OnBoarding/UserCharacter/SelectedUserCharacterScreen.swift
> [FIX] [DEL] SelectedImageName 에러 수정 및 불필요한 코드 제거

- MC2-LESSERAFIM/OnBoarding/CheckInComplete.swift
- MC2-LESSERAFIM/Profile/Modal/ImageModalScreen.swift
- MC2-LESSERAFIM/Profile/Modal/NameModalScreen.swift
- MC2-LESSERAFIM/Profile/ProfileScreen.swift
- CheckInComplete
- ImageModalScreen
- NameModalScreen
- ProfileScreen
> [MERGE] TextField 컴포넌트 및 디자인(색상 및 폰트 사이즈 및 레이아웃 등) 수정 머지 6

- MC2-LESSERAFIM/MC2_LESSERAFIM_App.swift
- MC2-LESSERAFIM/RecordCollection/RecordCollectionView.swift
- MC2-LESSERAFIM/landmarkData.json
> [MERGE] CoreData 합친 후 RecordCollectionView 에러 수정 

- MC2-LESSERAFIM/Challenge/Record/Painting/CanvusView.swift
- MC2-LESSERAFIM/OnBoarding/CheckInComplete.swift
- CheckInComplete
- CanvusView
> [MERGE] 디자인(색상 및 폰트 사이즈 및 레이아웃 등) 수정 및 Canvusview TextField 키보드 가려지는 현상 개선 머지 7

- MC2-LESSERAFIM/Challenge/RecordSelectionView.swift
- 사진 버튼 선택 시 액션시트 없앰
- 바로 사진 첨부 가능한 기록남기기 화면으로 이동
> [CORRECT] 수정사항 1번 '사진 촬영 동작 안함' 문제 '사진 첨부만 작동'으로 해결

- MC2-LESSERAFIM/RecordCollection/RecordCollectionView.swift
- 배경컬러 추가
- 긴 이미지 첨부 시 비율 이탈 문제 해결
- ignoreSafeArea 없앰 = 이미지로 화면 꽉 채울 수 없음
<hr />
> [CORRECT] 수정사항 18번 기록 선택 시 이미지 확대 문제 해결 v.2

- MC2-LESSERAFIM/Profile/ProfileScreen.swift
> [CHORE] 이 어플은 이제 FaceId가 되는"척" 합니다.

- MC2-LESSERAFIM/Challenge/ChallengeCheckScreen.swift
- MC2-LESSERAFIM/Challenge/RecordSelectionView.swift
> [MERGE] "필수 3. 챌린지 이름을 까먹음" 수정사항 반영

- MC2-LESSERAFIM/Challenge/ChallengeCheckScreen.swift
- MC2-LESSERAFIM/Challenge/ChallengeScreen.swift
- MC2-LESSERAFIM/Challenge/Record/Painting/CanvusView.swift
- MC2-LESSERAFIM/Challenge/Record/Picture/WritingView.swift
- MC2-LESSERAFIM/Challenge/Record/Writing/RecordWritingView.swift
- MC2-LESSERAFIM/ContentView.swift
> [Fix] fix bugs

- MC2-LESSERAFIM/Challenge/ChallengeCheckScreen.swift
- MC2-LESSERAFIM/Challenge/ChallengeScreen.swift
- MC2-LESSERAFIM/Challenge/NotYetChallengeScreen.swift
- MC2-LESSERAFIM/Challenge/Record/Painting/CanvusView.swift
- MC2-LESSERAFIM/Challenge/Record/Picture/WritingView.swift
- MC2-LESSERAFIM/Challenge/Record/RecordCompleteScreen.swift
- MC2-LESSERAFIM/Challenge/Record/Writing/RecordWritingView.swift
- MC2-LESSERAFIM/Challenge/RecordSelectionView.swift
add postedChallenge disable function
> [Add] postedChallenge disable

- MC2-LESSERAFIM.xcodeproj/project.pbxproj
- MC2-LESSERAFIM/ContentView.swift
- MC2-LESSERAFIM/RecordCollection/RecordCollectionView.swift
- (수정사항 17번) 탭바 아이콘 색상 변경
- (수정사항 23번) 썸네일 여백 없게 조정 -> 버그 수정하면서 코드가 롤백됐었던 듯
- ChallengeScreen PreView 없앰
> [CORRECT] 수정사항 17번 -> 탭바 아이콘 색상 변경

- MC2-LESSERAFIM/Components/CardView.swift
- 카드뷰 비율 오류 수정
- 카드가 이제 너무 자연스럽게 넘어갑니다.
- 거의 뭐 이탈리아 버터 먹음
> [CHORE]카드뷰 비율 오류 수정 <- Andy

- LaunchScreen.storyboard
- MC2-LESSERAFIM.xcodeproj/project.pbxproj
- 별도의 런치스크린 파일 생성
- General에서 해당 런치스크린 파일로 런치스크린 설정
> [ADD] 런치스크린 파일 생성

- MC2-LESSERAFIM/Components/CardView.swift
- MC2-LESSERAFIM/RecordCollection/RecordCollectionView.swift
- RecordCollectionView
- ThumbnailView
- DayLabel
- CategoryView
- CardView
> [MERGE] RecordCollectionView 디자인(색상 및 폰트 사이즈 및 레이아웃 등) 수정 머지 11

- MC2-LESSERAFIM/Components/CardView.swift
- MC2-LESSERAFIM/Components/CustomTextField.swift
- MC2-LESSERAFIM/RecordCollection/RecordCollectionView.swift
> [Add] add cardView

- MC2-LESSERAFIM/Profile/ProfileScreen.swift
> [ADD] 매일 6시 알림 푸시가 갑니다 <- Andy

- MC2-LESSERAFIM/Challenge/ChallengeScreen.swift
- MC2-LESSERAFIM/Components/CardView.swift
- MC2-LESSERAFIM/Components/CustomTextField.swift
- MC2-LESSERAFIM/RecordCollection/RecordCollectionView.swift
- CardView
- PopoverView
- TitleTextField
- RecordCollectionView
- GalleryView
- CategoryView
> [MERGE] CardView / PopoverView / TitleTextField / GalleryView 디자인 수정 12

- MC2-LESSERAFIM/Challenge/ChallengeCheckScreen.swift
- MC2-LESSERAFIM/Challenge/RecordSelectionView.swift
- ChallengeCheckScreen
- RecordSelectionView
> [MERGE] 챌린지 이름 설명 디자인 디테일 수정 13

- MC2-LESSERAFIM/Profile/ProfileScreen.swift
> [CHORE]이제 이 어플은 5분마다 "자기"를 찾습니다. <- Andy
